dependencies:
- name: node-react-yks
  version: 0.0.2
  repository: https://artifactory-tools.workshop-ocp46-four-bb0dafd08526894d1a8ae848e8bd8099-0000.eu-de.containers.appdomain.cloud/artifactory/generic-local/workshop-team-four